services:

  producer:
    container_name: producer
    build: .
    image: producer
    volumes:
      - type: bind
        source: ./producer.py
        target: /app/producer.py
      - type: bind
        source: ./reddit_ds.csv
        target: /app/reddit_ds.csv
    command: [ "./producer.py"]


