services:

  producer:
    container_name: producer
    build: .
    image: producer
    volumes:
      - type: bind
        source: ./producer.py
        target: /app/producer.py
    command: [ "./producer.py" , "tweets.csv"]
    networks:
      - my-net

  consumer:
    container_name: consumer
    build: .
    image: consumer
    volumes:
      - type: bind
        source: ./consumer.py
        target: /app/consumer.py
    command: [ "./consumer.py" ]
    networks:
      - my-net

  report:
    container_name: report
    build: .
    image: report
    volumes:
      - type: bind
        source: ./report.py
        target: /app/report.py
    command: [ "./report.py" ]
    networks:
      - my-net
    depends_on:
      consumer:
        condition: service_completed_successfully

networks:
  my-net:

