services:

  producer:
    container_name: producer
    build: .
    image: producer
    volumes:
      - type: bind
        source: ./producer.py
        target: /app/producer.py
    command: [ "./producer.py"]
    networks:
      - my-net

  consumer:
    container_name: consumer
    build: .
    image: consumer
    volumes:
      - type: bind
        source: ./consumer.py
        target: /app/consumer.py
    command: [ "./consumer.py" ]
    networks:
      - my-net

  reporter:
    container_name: reporter
    build: .
    image: reporter
    volumes:
      - type: bind
        source: ./reporter.py
        target: /app/reporter.py
    command: [ "./reporter.py" ]
    networks:
      - my-net
    depends_on:
      consumer:
        condition: service_completed_successfully

networks:
  my-net:

