services:

  init_kafka:
    container_name: init_kafka
    build: .
    image: producer
    volumes:
      - type: bind
        source: ./init_kafka.py
        target: /app/init_kafka.py
    command: [ "./init_kafka.py"]
    networks:
      - kafka-stack-docker-compose_default

  producer:
    container_name: producer
    build: .
    image: producer
    volumes:
      - type: bind
        source: ./producer.py
        target: /app/producer.py
      - type: bind
        source: ./reddit_ds.csv
        target: /app/reddit_ds.csv
    command: [ "./producer.py"]
    depends_on:
      - consumer
    networks:
      - kafka-stack-docker-compose_default
    environment:
      PRODUCERS: ${PRODUCERS}
      PARTITIONS: ${PARTITIONS}
      CONSUMERS: ${CONSUMERS}

  consumer:
    container_name: consumer
    build: .
    image: consumer
    volumes:
      - type: bind
        source: ./consumer.py
        target: /app/consumer.py
    command: [ "./consumer.py" ]
    depends_on:
      - postgres
      - init_kafka
    networks:
      - kafka-stack-docker-compose_default
    environment:
      PRODUCERS: ${PRODUCERS}
      PARTITIONS: ${PARTITIONS}
      CONSUMERS: ${CONSUMERS}

  reporter:
    container_name: reporter
    build: .
    image: reporter
    volumes:
      - type: bind
        source: ./reporter.py
        target: /app/reporter.py
      - type: bind
        source: ./report_output
        target: /app/report_output
    command: [ "./reporter.py" ]
    depends_on:
      consumer:
        condition: service_completed_successfully
    networks:
      - kafka-stack-docker-compose_default
    environment:
      PRODUCERS: ${PRODUCERS}
      PARTITIONS: ${PARTITIONS}
      CONSUMERS: ${CONSUMERS}

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: kafka_test
      POSTGRES_PASSWORD: kafka_test
      POSTGRES_DB: kafka_test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kafka_test"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5433:5432"
    networks:
      - kafka-stack-docker-compose_default

networks:
  kafka-stack-docker-compose_default:
    external: true

